# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy dependency definitions
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential gcc libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir fastmcp>=0.4.1 psutil>=7.0.0 pyside6>=6.8.2.1

# Copy application code
COPY . .

# Expose port if needed (stdio doesn't need)

# Default command
CMD ["python", "server.py"]
